In [1]:
%pip install rasterio
%pip install pillow
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# %% Cell: Setup & Imports
import os
import numpy as np
from PIL import Image

os.environ['SDL_AUDIODRIVER'] = 'dummy'  # Silence audio warnings
from utils.dem_processing import load_dem, get_placeholder_mask
from utils.game_map import build_base_game_map, combine_map
from utils.pathfinding import simulate_player
from utils.visualization import draw_path_on_grid

# %% Cell: Define File Paths
dem_path = 'Lidar_DEM_Hillshade/South_Clear_Creek_BareEarth_DEM_1m.tif'
road_mask_path = 'Roads_Boundary/South_Clear_Creek_Roads_Mask.tif'
grid_path = 'initial_grid.png'
output_path = 'path_overlay.png'

img = Image.open(road_mask_path).convert("L")
img_array = np.array(img)

inverted_array = np.where(img_array > 0, 255, 0).astype(np.uint8) # White roads
img_white_roads = Image.fromarray(inverted_array)
img_white_roads.save(grid_path)

# %% Cell: Process DEM to Create Placeholder Mask
dem_data = load_dem(dem_path)
placeholder_mask = get_placeholder_mask(dem_data)
print("Placeholder mask shape:", placeholder_mask.shape)

# %% Cell: Build and Combine the Game Map
base_game_map = build_base_game_map(grid_path)
combined_map = combine_map(base_game_map, placeholder_mask)
print("Combined game map:")
print(combined_map)

# %% Cell: Simulate Player Movement to Compute Path
# Optionally, you can set start_loc and reward_loc to fixed values; else, they are chosen randomly.
start_loc = None  # For random start; e.g., (0, 0) for fixed
reward_loc = None  # For random reward; e.g., (combined_map.shape[0]-1, combined_map.shape[1]-1)
path = simulate_player(combined_map, start=start_loc, reward=reward_loc)

# %% Cell: Visualize and Save the Path on the Grid
draw_path_on_grid(grid_path, path, output_path)


Maximum DEM value (assumed placeholder): 3.4e+38
Placeholder mask shape: (13115, 10460)
Unique pixel values in initial grid: [  0 255]
Base game map shape: (13115, 10460)
Combined game map created.
Combined game map:
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
